const BankLog = require('../models/BankLog');
const Order = require('../models/Order');
const Purchase = require('../models/Purchase');
const Transaction = require('../models/Transaction');

const getBankLogs = async (req, res) => {
  try {
    const { month, year, date } = req.query;
    let dateFilter = {};

    if (date) {
      const d = new Date(date);
      const startOfDay = new Date(d.getFullYear(), d.getMonth(), d.getDate(), 0, 0, 0, 0);
      const endOfDay = new Date(d.getFullYear(), d.getMonth(), d.getDate(), 23, 59, 59, 999);
      dateFilter = { $gte: startOfDay, $lte: endOfDay };
    } else if (month !== undefined && year !== undefined) {
      const m = parseInt(month);
      const y = parseInt(year);
      let startDate, endDate;
      if (m === 0) {
        startDate = new Date(y, 3, 1);
        endDate = new Date(y + 1, 2, 31, 23, 59, 59, 999);
      } else {
        const actualYear = m <= 3 ? y + 1 : y;
        startDate = new Date(actualYear, m - 1, 1);
        endDate = new Date(actualYear, m, 0, 23, 59, 59, 999);
      }
      dateFilter = { $gte: startDate, $lte: endDate };
    }

    // 1. Get manually added BankLog entries
    const manualLogsQuery = {
      companyId: req.user.companyId,
      ...(Object.keys(dateFilter).length ? { date: dateFilter } : {}),
      referenceId: { $exists: false }
    };
    const rawManualLogs = await BankLog.find(manualLogsQuery).sort({ date: -1 });
    const tempManualLogs = rawManualLogs.filter(l => l.paymentMode !== 'Cash');

    // Batch query transactions in date range to prevent N+1 queries
    const txQuery = {};
    if (Object.keys(dateFilter).length) {
      const padStart = new Date(dateFilter.$gte);
      padStart.setDate(padStart.getDate() - 2);
      const padEnd = new Date(dateFilter.$lte);
      padEnd.setDate(padEnd.getDate() + 2);
      txQuery.date = { $gte: padStart, $lte: padEnd };
    }
    const transactions = await Transaction.find(txQuery).populate('partyId', 'name');

    const manualLogs = [];
    for (const log of tempManualLogs) {
      let logObj = log.toObject ? log.toObject() : log;
      if (logObj.description === 'Payment towards due balance' || !logObj.description) {
        const logDate = new Date(logObj.date).getTime();
        const startMs = logDate - 24 * 60 * 60 * 1000;
        const endMs = logDate + 2 * 24 * 60 * 60 * 1000;
        
        const matchingTx = transactions.find(tx => 
          tx.amount === logObj.amount &&
          new Date(tx.date).getTime() >= startMs &&
          new Date(tx.date).getTime() <= endMs
        );
        
        if (matchingTx && matchingTx.partyId) {
          logObj.description = `Payment ${logObj.type === 'IN' ? 'from' : 'to'} ${matchingTx.partyId.name}`;
        }
      }
      manualLogs.push(logObj);
    }

    // 2. Get ALL orders for the period
    const orderQuery = { companyId: req.user.companyId };
    if (Object.keys(dateFilter).length) orderQuery.date = dateFilter;
    const orders = await Order.find(orderQuery).sort({ date: -1 });

    // 3. Get all purchases for the period
    const purchaseQuery = { companyId: req.user.companyId };
    if (Object.keys(dateFilter).length) purchaseQuery.date = dateFilter;
    const purchases = await Purchase.find(purchaseQuery).populate('partyId', 'name').sort({ date: -1 });

    // Convert orders to BankLog-shaped entries
    const orderLogs = orders
      .filter(o => ['Online/UPI', 'Online', 'UPI', 'Bank Transfer', 'Split'].includes(o.paymentMode))
      .filter(o => (o.paymentMode === 'Split' ? o.paidOnline > 0 : o.paidAmount > 0))
      .map(o => ({
        _id: `order_${o._id}`,
        type: 'IN',
        category: 'Sale',
        amount: o.paymentMode === 'Split' ? o.paidOnline : o.paidAmount,
        description: o.customerName || 'Customer',
        paymentMode: o.paymentMode === 'Split' ? 'UPI' : o.paymentMode,
        date: o.date,
        createdAt: o.createdAt,
        isAutoGenerated: true,
        paymentStatus: o.paymentStatus
      }));

    // Convert purchases to BankLog-shaped entries (ONLY Online/UPI or Split with Online payment)
    const purchaseLogs = purchases
      .filter(p => p.status === 'Online/UPI' || p.status === 'Online' || (p.status === 'Split' && p.paidOnline > 0))
      .map(p => {
        let amount = p.totalCost || p.cost || 0;
        if (p.status === 'Split') amount = p.paidOnline;
        
        const vendorName = p.partyId ? p.partyId.name : (p.supplier || 'Vendor');
        const itemNames = p.items && p.items.length > 0 ? p.items.map(i => i.name).join(', ') : (p.item || 'Items');

        return {
          _id: `purchase_${p._id}`,
          type: 'OUT',
          category: 'Purchase',
          amount: amount,
          description: vendorName,
          paymentMode: p.status === 'Split' ? 'Online/UPI' : p.status,
          date: p.date,
          createdAt: p.createdAt,
          isAutoGenerated: true
        };
      });

    // Combine all logs and sort by date descending
    const allLogs = [...manualLogs, ...orderLogs, ...purchaseLogs].sort((a, b) => {
      const dateDiff = new Date(b.date).getTime() - new Date(a.date).getTime();
      if (dateDiff === 0) {
        const timeB = b.createdAt ? new Date(b.createdAt).getTime() : 0;
        const timeA = a.createdAt ? new Date(a.createdAt).getTime() : 0;
        return timeB - timeA;
      }
      return dateDiff;
    });

    // Calculate stats
    const totalIn = allLogs.filter(l => l.type === 'IN').reduce((acc, l) => acc + l.amount, 0);
    const totalOut = allLogs.filter(l => l.type === 'OUT').reduce((acc, l) => acc + l.amount, 0);

    res.json({
      logs: allLogs,
      stats: {
        totalIn,
        totalOut,
        balance: totalIn - totalOut
      }
    });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

const addBankLog = async (req, res) => {
  try {
    const newLog = new BankLog({
      ...req.body,
      companyId: req.user.companyId
    });
    await newLog.save();
    res.status(201).json(newLog);
  } catch (error) {
    res.status(400).json({ message: error.message });
  }
};

const deleteBankLog = async (req, res) => {
  try {
    const log = await BankLog.findOne({ _id: req.params.id, companyId: req.user.companyId });
    if (!log) return res.status(404).json({ message: 'Log not found' });
    if (log.referenceId) return res.status(400).json({ message: 'Cannot delete auto-generated system entries directly.' });
    
    await BankLog.deleteOne({ _id: req.params.id });
    res.json({ message: 'Deleted successfully' });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

module.exports = {
  getBankLogs,
  addBankLog,
  deleteBankLog
};
